export const colors = {
  primary: '#2563eb',
  primaryLight: '#3b82f6',
  primaryDark: '#1d4ed8',
  primaryBg: '#eff6ff',
  primaryBorder: '#bfdbfe',
  success: '#16a34a',
  successLight: '#22c55e',
  successBg: '#f0fdf4',
  successBorder: '#a7f3d0',
  warning: '#f59e0b',
  warningDark: '#d97706',
  warningBg: '#fffbeb',
  warningBorder: '#fde68a',
  warningText: '#92400e',
  danger: '#dc2626',
  dangerLight: '#ef4444',
  dangerBg: '#fef2f2',
  dangerBorder: '#fca5a5',
  dangerText: '#b91c1c',
  purple: '#7c3aed',
  purpleBg: '#f5f3ff',
  purpleBorder: '#c4b5fd',
  background: '#f8fafc',
  surface: '#ffffff',
  surfaceElevated: '#ffffff',
  border: '#e2e8f0',
  borderLight: '#f1f5f9',
  textPrimary: '#1a1a1a',
  textSecondary: '#374151',
  textTertiary: '#64748b',
  textDisabled: '#94a3b8',
  textInverse: '#ffffff',
  overlay: 'rgba(0, 0, 0, 0.5)',
  overlayLight: 'rgba(0, 0, 0, 0.15)',
  surfaceOverlay: 'rgba(255, 255, 255, 0.6)',
  subtleBg: 'rgba(0, 0, 0, 0.1)',
} as const;

export const typography = {
  heading1: { fontSize: 32, fontWeight: '800' as const, letterSpacing: -0.5 },
  heading2: { fontSize: 24, fontWeight: '700' as const, letterSpacing: -0.3 },
  heading3: { fontSize: 20, fontWeight: '700' as const },
  heading4: { fontSize: 17, fontWeight: '600' as const },
  body: { fontSize: 15, fontWeight: '400' as const, lineHeight: 22 },
  bodyMedium: { fontSize: 15, fontWeight: '500' as const, lineHeight: 22 },
  bodySemiBold: { fontSize: 15, fontWeight: '600' as const, lineHeight: 22 },
  caption: { fontSize: 13, fontWeight: '400' as const, lineHeight: 18 },
  captionMedium: { fontSize: 13, fontWeight: '500' as const },
  label: { fontSize: 14, fontWeight: '600' as const },
  overline: { fontSize: 12, fontWeight: '600' as const, letterSpacing: 1, textTransform: 'uppercase' as const },
  buttonLarge: { fontSize: 17, fontWeight: '600' as const },
  buttonDefault: { fontSize: 16, fontWeight: '600' as const },
  buttonSmall: { fontSize: 14, fontWeight: '600' as const },
  number: { fontSize: 28, fontWeight: '800' as const },
  numberSmall: { fontSize: 18, fontWeight: '700' as const },
} as const;

export const spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 40,
} as const;

export const radius = {
  sm: 6,
  md: 10,
  lg: 12,
  xl: 16,
  xxl: 20,
  pill: 999,
  circle: 9999,
} as const;

export const shadows = {
  none: {},
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
} as const;

export const durations = {
  fast: 150,
  normal: 250,
  slow: 400,
  entrance: 350,
} as const;
